project:
  title: "dolt-git-for-data"
  output-dir: _slides

format:
  revealjs: 
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    logo: images/d4dm_neg.png
    css: styles.css
    footer: "[Data for Decision Makers](https://d4dm.org)"

author:
  name: Ernest Guevarra
  email: ernest@guevarra.io
  #affiliation: University of Oxford